# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Lachesis Gohugo Theme"
license = "MIT"
licenselink = "https://github.com/ajduncan/gohugo-theme-lachesis/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://github.com/ajduncan/gohugo-theme-lachesis"
tags = ["website", "starter", "responsive", "Disqus", "blog", "tachyons"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = 0.30.2

[author]
  name = "Andy Duncan"
  homepage = "https://github.com/ajduncan"
